refactor format.js
pygame-guide-for-sneks/pygame-guide-for-sneks.github.io pull request #101
Opened 2023-03-01 16:26 UTC by pycoinfu

2023-03-01 16:31 UTC, SSS-Says-Snek requested changes

2023-03-01 16:31 UTC, SSS-Says-Snek commented on guide/scripts/format.js
> +    tablOfContents.innerHTML = html;
Typo

2023-03-01 16:57 UTC, pycoinfu commented on guide/scripts/format.js
> +    tablOfContents.innerHTML = html;
Thanks for pointing that out!

2023-03-01 20:54 UTC, SSS-Says-Snek approved these changes
LGTM!

2023-04-18 01:55 UTC, oddbookworm approved these changes
LGTM

2023-04-18 01:57 UTC, merged