Elaborating exiting pygame applications
pygame-guide-for-sneks/pygame-guide-for-sneks.github.io pull request #53
Opened 2022-08-15 07:31 UTC by blankRiot96

Covered a few different styles of exiting a `pygame` application and the benefits of each.

2022-08-15 16:08 UTC, oddbookworm commented
This looks good, but there is one other way that I've used before:
If your game loop is in a function like `main`, then just `return` after the `QUIT` event works too. Not sure that one should be mentioned though

2022-08-15 17:17 UTC, oddbookworm submitted a review, later dismissed
LGTM

2022-08-15 17:29 UTC, blankRiot96 commented
Had mentioned on discord too: You are right and that is indeed a valid way to exit the application! But I don't think you would see it in a more structural larger game(mostly because there is some complexity involved to work around it for it to be used) and I want to build the foundation for that! 
But it is definitely a valid thing and it may have been worth mentioning if I had a `main` function already. Unfortunately I did not create a `main` function to contain my code to keep it as simple as possible

2022-08-16 19:35 UTC, pycoinfu requested changes

2022-08-16 19:35 UTC, pycoinfu commented on intro/setup/index.html
>  while True:
Instead of `while True` it should be `while is_running`, otherwise `is_running` isn't doing anything

2022-12-24 03:55 UTC, oddbookworm commented
#61 replaced this PR, so I'm closing it

2022-12-24 03:55 UTC, closed without merging